version: '3'

services:
    mysql-docker-container:
        image: mysql:latest
        environment: 
           - MYSQL_ROOT_PASSWORD=mamnomam
           - MYSQL_DATABASE=blogdata
           - MYSQL_USER=blog
           - MYSQL_PASSWORD=blog
        ports:
          - 3307:3306
        volumes:
           - ./startscript.sql:/docker-entrypoint-initdb.d/dump.sql
    spring-boot-app:
        image: spring-boot-app-image
        build:
            context: ./
            dockerfile: Dockerfile
        depends_on:
            - mysql-docker-container
        ports:
            - 8087:8080
        volumes:
            - /data/spring-boot-app
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        depends_on:
          - mysql-docker-container
        restart: always
        ports:
          - "8082:80"
        environment:
         - PMA_ARBITRARY=1
         - PMA_HOST:mysql-docker-container
         - PMA_PORT:3306
