-- MySQL Script generated by MySQL Workbench
-- Sat Aug 25 12:16:16 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema blogdata
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema blogdata
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `blogdata` DEFAULT CHARACTER SET utf8 ;
USE `blogdata` ;

-- -----------------------------------------------------
-- Table `blogdata`.`site`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `blogdata`.`site` ;

CREATE TABLE IF NOT EXISTS `blogdata`.`site` (
  `sitename` VARCHAR(20) NOT NULL,
  `description` VARCHAR(45) NULL,
  `owner` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`sitename`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blogdata`.`pages`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `blogdata`.`pages` ;

CREATE TABLE IF NOT EXISTS `blogdata`.`pages` (
  `pageid` INT NOT NULL AUTO_INCREMENT,
  `pagename` VARCHAR(45) NOT NULL,
  `site_sitename` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`pageid`),
  INDEX `fk_pages_site_idx` (`site_sitename` ASC),
  CONSTRAINT `fk_pages_site`
    FOREIGN KEY (`site_sitename`)
    REFERENCES `blogdata`.`site` (`sitename`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blogdata`.`posts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `blogdata`.`posts` ;

CREATE TABLE IF NOT EXISTS `blogdata`.`posts` (
  `postid` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(200) NOT NULL,
  `preview` MEDIUMTEXT NOT NULL,
  `content` LONGTEXT NOT NULL,
  `image` LONGTEXT NULL,
  `pages_pageid` INT NOT NULL,
  `date` DATE NULL,
  PRIMARY KEY (`postid`),
  INDEX `fk_posts_pages1_idx` (`pages_pageid` ASC),
  CONSTRAINT `fk_posts_pages1`
    FOREIGN KEY (`pages_pageid`)
    REFERENCES `blogdata`.`pages` (`pageid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blogdata`.`categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `blogdata`.`categories` ;

CREATE TABLE IF NOT EXISTS `blogdata`.`categories` (
  `categoryid` INT NOT NULL AUTO_INCREMENT,
  `category` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`categoryid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blogdata`.`categories_has_posts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `blogdata`.`categories_has_posts` ;

CREATE TABLE IF NOT EXISTS `blogdata`.`categories_has_posts` (
  `categories_categoryid` INT NOT NULL,
  `posts_postid` INT NOT NULL,
  PRIMARY KEY (`categories_categoryid`, `posts_postid`),
  INDEX `fk_categories_has_posts_posts1_idx` (`posts_postid` ASC),
  INDEX `fk_categories_has_posts_categories1_idx` (`categories_categoryid` ASC),
  CONSTRAINT `fk_categories_has_posts_categories1`
    FOREIGN KEY (`categories_categoryid`)
    REFERENCES `blogdata`.`categories` (`categoryid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_categories_has_posts_posts1`
    FOREIGN KEY (`posts_postid`)
    REFERENCES `blogdata`.`posts` (`postid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blogdata`.`widgets`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `blogdata`.`widgets` ;

CREATE TABLE IF NOT EXISTS `blogdata`.`widgets` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `header` VARCHAR(45) NOT NULL,
  `body` LONGTEXT NOT NULL,
  `site_sitename` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_widgets_site1_idx` (`site_sitename` ASC),
  CONSTRAINT `fk_widgets_site1`
    FOREIGN KEY (`site_sitename`)
    REFERENCES `blogdata`.`site` (`sitename`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;



INSERT INTO `blogdata`.`site` (`sitename`, `description`, `owner`) VALUES ('Myblog', 'This is my blog', 'Bartek');
INSERT INTO `blogdata`.`pages` (`pagename`, `site_sitename`) VALUES ('Home', 'Myblog');
INSERT INTO `blogdata`.`pages` (`pagename`, `site_sitename`) VALUES ('About me', 'Myblog');
INSERT INTO `blogdata`.`pages` (`pagename`, `site_sitename`) VALUES ('Contact', 'Myblog');

INSERT INTO `blogdata`.`posts` (`title`, `preview`, `content`, `image`, `pages_pageid`, `date`) VALUES ('Lorem ipsum', 'Integer ligula erat, iaculis a sodales eu, commodo nec lorem. Nam efficitur tellus vitae sem tincidunt aliquet. Aliquam dolor turpis, eleifend eget nis', 'Integer ligula erat, iaculis a sodales eu, commodo nec lorem. Nam efficitur tellus vitae sem tincidunt aliquet. Aliquam dolor turpis, eleifend eget nisi id, interdum faucibus lacus. In hac habitasse platea dictumst. Nulla metus nulla, aliquet a eleifend vel, lacinia eget sem. Mauris eu lacinia elit. Nam hendrerit, libero sed euismod tempus, dolor enim consequat risus, eu maximus ligula quam at mauris. Proin at semper justo. Vivamus lacinia vel enim eget bibendum. Ut eget leo nec elit auctor facilisis maximus in quam. Maecenas ullamcorper ullamcorper nulla, eu fringilla mi eleifend eget. Ut diam nulla, suscipit sit amet augue vitae, dapibus viverra nunc. Aliquam consequat urna ipsum, at hendrerit diam pharetra eget. Nulla tincidunt ultricies enim, at maximus metus semper nec. Morbi at libero et ipsum convallis congue.

', 'image.jpg', '1', '2018-02-03');
INSERT INTO `blogdata`.`posts` (`title`, `preview`, `content`, `image`, `pages_pageid`, `date`) VALUES ('1 orem ipsum', 'Integer ligula erat, iaculis a sodales eu, commodo nec lorem. Nam efficitur tellus vitae sem tincidunt aliquet. Aliquam dolor turpis, eleifend eget nis', 'Integer ligula erat, iaculis a sodales eu, commodo nec lorem. Nam efficitur tellus vitae sem tincidunt aliquet. Aliquam dolor turpis, eleifend eget nisi id, interdum faucibus lacus. In hac habitasse platea dictumst. Nulla metus nulla, aliquet a eleifend vel, lacinia eget sem. Mauris eu lacinia elit. Nam hendrerit, libero sed euismod tempus, dolor enim consequat risus, eu maximus ligula quam at mauris. Proin at semper justo. Vivamus lacinia vel enim eget bibendum. Ut eget leo nec elit auctor facilisis maximus in quam. Maecenas ullamcorper ullamcorper nulla, eu fringilla mi eleifend eget. Ut diam nulla, suscipit sit amet augue vitae, dapibus viverra nunc. Aliquam consequat urna ipsum, at hendrerit diam pharetra eget. Nulla tincidunt ultricies enim, at maximus metus semper nec. Morbi at libero et ipsum convallis congue.

', 'image.jpg', '2', '2018-02-03');
INSERT INTO `blogdata`.`posts` (`title`, `preview`, `content`, `image`, `pages_pageid`, `date`) VALUES ('3 orem ipsum', 'Integer ligula erat, iaculis a sodales eu, commodo nec lorem. Nam efficitur tellus vitae sem tincidunt aliquet. Aliquam dolor turpis, eleifend eget nis', 'Integer ligula erat, iaculis a sodales eu, commodo nec lorem. Nam efficitur tellus vitae sem tincidunt aliquet. Aliquam dolor turpis, eleifend eget nisi id, interdum faucibus lacus. In hac habitasse platea dictumst. Nulla metus nulla, aliquet a eleifend vel, lacinia eget sem. Mauris eu lacinia elit. Nam hendrerit, libero sed euismod tempus, dolor enim consequat risus, eu maximus ligula quam at mauris. Proin at semper justo. Vivamus lacinia vel enim eget bibendum. Ut eget leo nec elit auctor facilisis maximus in quam. Maecenas ullamcorper ullamcorper nulla, eu fringilla mi eleifend eget. Ut diam nulla, suscipit sit amet augue vitae, dapibus viverra nunc. Aliquam consequat urna ipsum, at hendrerit diam pharetra eget. Nulla tincidunt ultricies enim, at maximus metus semper nec. Morbi at libero et ipsum convallis congue.

', 'image.jpg', '2', '2018-02-03');
INSERT INTO `blogdata`.`posts` (`title`, `preview`, `content`, `image`, `pages_pageid`, `date`) VALUES ('4 orem ipsum', 'Integer ligula erat, iaculis a sodales eu, commodo nec lorem. Nam efficitur tellus vitae sem tincidunt aliquet. Aliquam dolor turpis, eleifend eget nis', 'Integer ligula erat, iaculis a sodales eu, commodo nec lorem. Nam efficitur tellus vitae sem tincidunt aliquet. Aliquam dolor turpis, eleifend eget nisi id, interdum faucibus lacus. In hac habitasse platea dictumst. Nulla metus nulla, aliquet a eleifend vel, lacinia eget sem. Mauris eu lacinia elit. Nam hendrerit, libero sed euismod tempus, dolor enim consequat risus, eu maximus ligula quam at mauris. Proin at semper justo. Vivamus lacinia vel enim eget bibendum. Ut eget leo nec elit auctor facilisis maximus in quam. Maecenas ullamcorper ullamcorper nulla, eu fringilla mi eleifend eget. Ut diam nulla, suscipit sit amet augue vitae, dapibus viverra nunc. Aliquam consequat urna ipsum, at hendrerit diam pharetra eget. Nulla tincidunt ultricies enim, at maximus metus semper nec. Morbi at libero et ipsum convallis congue.

', 'image.jpg', '2', '2018-02-03');
INSERT INTO `blogdata`.`posts` (`title`, `preview`, `content`, `image`, `pages_pageid`, `date`) VALUES ('5 orem ipsum', 'Integer ligula erat, iaculis a sodales eu, commodo nec lorem. Nam efficitur tellus vitae sem tincidunt aliquet. Aliquam dolor turpis, eleifend eget nis', 'Integer ligula erat, iaculis a sodales eu, commodo nec lorem. Nam efficitur tellus vitae sem tincidunt aliquet. Aliquam dolor turpis, eleifend eget nisi id, interdum faucibus lacus. In hac habitasse platea dictumst. Nulla metus nulla, aliquet a eleifend vel, lacinia eget sem. Mauris eu lacinia elit. Nam hendrerit, libero sed euismod tempus, dolor enim consequat risus, eu maximus ligula quam at mauris. Proin at semper justo. Vivamus lacinia vel enim eget bibendum. Ut eget leo nec elit auctor facilisis maximus in quam. Maecenas ullamcorper ullamcorper nulla, eu fringilla mi eleifend eget. Ut diam nulla, suscipit sit amet augue vitae, dapibus viverra nunc. Aliquam consequat urna ipsum, at hendrerit diam pharetra eget. Nulla tincidunt ultricies enim, at maximus metus semper nec. Morbi at libero et ipsum convallis congue.

', 'image.jpg', '2', '2018-02-03');
INSERT INTO `blogdata`.`posts` (`title`, `preview`, `content`, `image`, `pages_pageid`, `date`) VALUES ('6 orem ipsum', 'Integer ligula erat, iaculis a sodales eu, commodo nec lorem. Nam efficitur tellus vitae sem tincidunt aliquet. Aliquam dolor turpis, eleifend eget nis', 'Integer ligula erat, iaculis a sodales eu, commodo nec lorem. Nam efficitur tellus vitae sem tincidunt aliquet. Aliquam dolor turpis, eleifend eget nisi id, interdum faucibus lacus. In hac habitasse platea dictumst. Nulla metus nulla, aliquet a eleifend vel, lacinia eget sem. Mauris eu lacinia elit. Nam hendrerit, libero sed euismod tempus, dolor enim consequat risus, eu maximus ligula quam at mauris. Proin at semper justo. Vivamus lacinia vel enim eget bibendum. Ut eget leo nec elit auctor facilisis maximus in quam. Maecenas ullamcorper ullamcorper nulla, eu fringilla mi eleifend eget. Ut diam nulla, suscipit sit amet augue vitae, dapibus viverra nunc. Aliquam consequat urna ipsum, at hendrerit diam pharetra eget. Nulla tincidunt ultricies enim, at maximus metus semper nec. Morbi at libero et ipsum convallis congue.

', 'image.jpg', '2', '2018-02-03');
INSERT INTO `blogdata`.`posts` (`title`, `preview`, `content`, `image`, `pages_pageid`, `date`) VALUES ('7 orem ipsum', 'Integer ligula erat, iaculis a sodales eu, commodo nec lorem. Nam efficitur tellus vitae sem tincidunt aliquet. Aliquam dolor turpis, eleifend eget nis', 'Integer ligula erat, iaculis a sodales eu, commodo nec lorem. Nam efficitur tellus vitae sem tincidunt aliquet. Aliquam dolor turpis, eleifend eget nisi id, interdum faucibus lacus. In hac habitasse platea dictumst. Nulla metus nulla, aliquet a eleifend vel, lacinia eget sem. Mauris eu lacinia elit. Nam hendrerit, libero sed euismod tempus, dolor enim consequat risus, eu maximus ligula quam at mauris. Proin at semper justo. Vivamus lacinia vel enim eget bibendum. Ut eget leo nec elit auctor facilisis maximus in quam. Maecenas ullamcorper ullamcorper nulla, eu fringilla mi eleifend eget. Ut diam nulla, suscipit sit amet augue vitae, dapibus viverra nunc. Aliquam consequat urna ipsum, at hendrerit diam pharetra eget. Nulla tincidunt ultricies enim, at maximus metus semper nec. Morbi at libero et ipsum convallis congue.

', 'image.jpg', '2', '2018-02-03');
INSERT INTO `blogdata`.`posts` (`title`, `preview`, `content`, `image`, `pages_pageid`, `date`) VALUES ('8 orem ipsum', 'Integer ligula erat, iaculis a sodales eu, commodo nec lorem. Nam efficitur tellus vitae sem tincidunt aliquet. Aliquam dolor turpis, eleifend eget nis', 'Integer ligula erat, iaculis a sodales eu, commodo nec lorem. Nam efficitur tellus vitae sem tincidunt aliquet. Aliquam dolor turpis, eleifend eget nisi id, interdum faucibus lacus. In hac habitasse platea dictumst. Nulla metus nulla, aliquet a eleifend vel, lacinia eget sem. Mauris eu lacinia elit. Nam hendrerit, libero sed euismod tempus, dolor enim consequat risus, eu maximus ligula quam at mauris. Proin at semper justo. Vivamus lacinia vel enim eget bibendum. Ut eget leo nec elit auctor facilisis maximus in quam. Maecenas ullamcorper ullamcorper nulla, eu fringilla mi eleifend eget. Ut diam nulla, suscipit sit amet augue vitae, dapibus viverra nunc. Aliquam consequat urna ipsum, at hendrerit diam pharetra eget. Nulla tincidunt ultricies enim, at maximus metus semper nec. Morbi at libero et ipsum convallis congue.

', 'image.jpg', '2', '2018-02-03');
INSERT INTO `blogdata`.`posts` (`title`, `preview`, `content`, `image`, `pages_pageid`, `date`) VALUES ('9 orem ipsum', 'Integer ligula erat, iaculis a sodales eu, commodo nec lorem. Nam efficitur tellus vitae sem tincidunt aliquet. Aliquam dolor turpis, eleifend eget nis', 'Integer ligula erat, iaculis a sodales eu, commodo nec lorem. Nam efficitur tellus vitae sem tincidunt aliquet. Aliquam dolor turpis, eleifend eget nisi id, interdum faucibus lacus. In hac habitasse platea dictumst. Nulla metus nulla, aliquet a eleifend vel, lacinia eget sem. Mauris eu lacinia elit. Nam hendrerit, libero sed euismod tempus, dolor enim consequat risus, eu maximus ligula quam at mauris. Proin at semper justo. Vivamus lacinia vel enim eget bibendum. Ut eget leo nec elit auctor facilisis maximus in quam. Maecenas ullamcorper ullamcorper nulla, eu fringilla mi eleifend eget. Ut diam nulla, suscipit sit amet augue vitae, dapibus viverra nunc. Aliquam consequat urna ipsum, at hendrerit diam pharetra eget. Nulla tincidunt ultricies enim, at maximus metus semper nec. Morbi at libero et ipsum convallis congue.

', 'image.jpg', '2', '2018-02-03');
INSERT INTO `blogdata`.`posts` (`title`, `preview`, `content`, `image`, `pages_pageid`, `date`) VALUES ('10 orem ipsum', 'Integer ligula erat, iaculis a sodales eu, commodo nec lorem. Nam efficitur tellus vitae sem tincidunt aliquet. Aliquam dolor turpis, eleifend eget nis', 'Integer ligula erat, iaculis a sodales eu, commodo nec lorem. Nam efficitur tellus vitae sem tincidunt aliquet. Aliquam dolor turpis, eleifend eget nisi id, interdum faucibus lacus. In hac habitasse platea dictumst. Nulla metus nulla, aliquet a eleifend vel, lacinia eget sem. Mauris eu lacinia elit. Nam hendrerit, libero sed euismod tempus, dolor enim consequat risus, eu maximus ligula quam at mauris. Proin at semper justo. Vivamus lacinia vel enim eget bibendum. Ut eget leo nec elit auctor facilisis maximus in quam. Maecenas ullamcorper ullamcorper nulla, eu fringilla mi eleifend eget. Ut diam nulla, suscipit sit amet augue vitae, dapibus viverra nunc. Aliquam consequat urna ipsum, at hendrerit diam pharetra eget. Nulla tincidunt ultricies enim, at maximus metus semper nec. Morbi at libero et ipsum convallis congue.

', 'image.jpg', '2', '2018-02-03');
INSERT INTO `blogdata`.`posts` (`title`, `preview`, `content`, `image`, `pages_pageid`, `date`) VALUES ('11 orem ipsum', 'Integer ligula erat, iaculis a sodales eu, commodo nec lorem. Nam efficitur tellus vitae sem tincidunt aliquet. Aliquam dolor turpis, eleifend eget nis', 'Integer ligula erat, iaculis a sodales eu, commodo nec lorem. Nam efficitur tellus vitae sem tincidunt aliquet. Aliquam dolor turpis, eleifend eget nisi id, interdum faucibus lacus. In hac habitasse platea dictumst. Nulla metus nulla, aliquet a eleifend vel, lacinia eget sem. Mauris eu lacinia elit. Nam hendrerit, libero sed euismod tempus, dolor enim consequat risus, eu maximus ligula quam at mauris. Proin at semper justo. Vivamus lacinia vel enim eget bibendum. Ut eget leo nec elit auctor facilisis maximus in quam. Maecenas ullamcorper ullamcorper nulla, eu fringilla mi eleifend eget. Ut diam nulla, suscipit sit amet augue vitae, dapibus viverra nunc. Aliquam consequat urna ipsum, at hendrerit diam pharetra eget. Nulla tincidunt ultricies enim, at maximus metus semper nec. Morbi at libero et ipsum convallis congue.

', 'image.jpg', '2', '2018-02-03');
INSERT INTO `blogdata`.`posts` (`title`, `preview`, `content`, `image`, `pages_pageid`, `date`) VALUES ('12 orem ipsum', 'Integer ligula erat, iaculis a sodales eu, commodo nec lorem. Nam efficitur tellus vitae sem tincidunt aliquet. Aliquam dolor turpis, eleifend eget nis', 'Integer ligula erat, iaculis a sodales eu, commodo nec lorem. Nam efficitur tellus vitae sem tincidunt aliquet. Aliquam dolor turpis, eleifend eget nisi id, interdum faucibus lacus. In hac habitasse platea dictumst. Nulla metus nulla, aliquet a eleifend vel, lacinia eget sem. Mauris eu lacinia elit. Nam hendrerit, libero sed euismod tempus, dolor enim consequat risus, eu maximus ligula quam at mauris. Proin at semper justo. Vivamus lacinia vel enim eget bibendum. Ut eget leo nec elit auctor facilisis maximus in quam. Maecenas ullamcorper ullamcorper nulla, eu fringilla mi eleifend eget. Ut diam nulla, suscipit sit amet augue vitae, dapibus viverra nunc. Aliquam consequat urna ipsum, at hendrerit diam pharetra eget. Nulla tincidunt ultricies enim, at maximus metus semper nec. Morbi at libero et ipsum convallis congue.

', 'image.jpg', '2', '2018-02-03');
INSERT INTO `blogdata`.`posts` (`title`, `preview`, `content`, `image`, `pages_pageid`, `date`) VALUES ('13 orem ipsum', 'Integer ligula erat, iaculis a sodales eu, commodo nec lorem. Nam efficitur tellus vitae sem tincidunt aliquet. Aliquam dolor turpis, eleifend eget nis', 'Integer ligula erat, iaculis a sodales eu, commodo nec lorem. Nam efficitur tellus vitae sem tincidunt aliquet. Aliquam dolor turpis, eleifend eget nisi id, interdum faucibus lacus. In hac habitasse platea dictumst. Nulla metus nulla, aliquet a eleifend vel, lacinia eget sem. Mauris eu lacinia elit. Nam hendrerit, libero sed euismod tempus, dolor enim consequat risus, eu maximus ligula quam at mauris. Proin at semper justo. Vivamus lacinia vel enim eget bibendum. Ut eget leo nec elit auctor facilisis maximus in quam. Maecenas ullamcorper ullamcorper nulla, eu fringilla mi eleifend eget. Ut diam nulla, suscipit sit amet augue vitae, dapibus viverra nunc. Aliquam consequat urna ipsum, at hendrerit diam pharetra eget. Nulla tincidunt ultricies enim, at maximus metus semper nec. Morbi at libero et ipsum convallis congue.

', 'image.jpg', '2', '2018-02-03');
INSERT INTO `blogdata`.`posts` (`title`, `preview`, `content`, `image`, `pages_pageid`, `date`) VALUES ('2 orem ipsum', 'Integer ligula erat, iaculis a sodales eu, commodo nec lorem. Nam efficitur tellus vitae sem tincidunt aliquet. Aliquam dolor turpis, eleifend eget nis', 'Integer ligula erat, iaculis a sodales eu, commodo nec lorem. Nam efficitur tellus vitae sem tincidunt aliquet. Aliquam dolor turpis, eleifend eget nisi id, interdum faucibus lacus. In hac habitasse platea dictumst. Nulla metus nulla, aliquet a eleifend vel, lacinia eget sem. Mauris eu lacinia elit. Nam hendrerit, libero sed euismod tempus, dolor enim consequat risus, eu maximus ligula quam at mauris. Proin at semper justo. Vivamus lacinia vel enim eget bibendum. Ut eget leo nec elit auctor facilisis maximus in quam. Maecenas ullamcorper ullamcorper nulla, eu fringilla mi eleifend eget. Ut diam nulla, suscipit sit amet augue vitae, dapibus viverra nunc. Aliquam consequat urna ipsum, at hendrerit diam pharetra eget. Nulla tincidunt ultricies enim, at maximus metus semper nec. Morbi at libero et ipsum convallis congue.

', 'image.jpg', '2', '2018-02-03');
INSERT INTO `blogdata`.`posts` (`title`, `preview`, `content`, `image`, `pages_pageid`, `date`) VALUES ('2 orem ipsum', 'Integer ligula erat, iaculis a sodales eu, commodo nec lorem. Nam efficitur tellus vitae sem tincidunt aliquet. Aliquam dolor turpis, eleifend eget nis', 'Integer ligula erat, iaculis a sodales eu, commodo nec lorem. Nam efficitur tellus vitae sem tincidunt aliquet. Aliquam dolor turpis, eleifend eget nisi id, interdum faucibus lacus. In hac habitasse platea dictumst. Nulla metus nulla, aliquet a eleifend vel, lacinia eget sem. Mauris eu lacinia elit. Nam hendrerit, libero sed euismod tempus, dolor enim consequat risus, eu maximus ligula quam at mauris. Proin at semper justo. Vivamus lacinia vel enim eget bibendum. Ut eget leo nec elit auctor facilisis maximus in quam. Maecenas ullamcorper ullamcorper nulla, eu fringilla mi eleifend eget. Ut diam nulla, suscipit sit amet augue vitae, dapibus viverra nunc. Aliquam consequat urna ipsum, at hendrerit diam pharetra eget. Nulla tincidunt ultricies enim, at maximus metus semper nec. Morbi at libero et ipsum convallis congue.

', 'image.jpg', '2', '2018-02-03');
INSERT INTO `blogdata`.`posts` (`title`, `preview`, `content`, `image`, `pages_pageid`, `date`) VALUES ('2 orem ipsum', 'Integer ligula erat, iaculis a sodales eu, commodo nec lorem. Nam efficitur tellus vitae sem tincidunt aliquet. Aliquam dolor turpis, eleifend eget nis', 'Integer ligula erat, iaculis a sodales eu, commodo nec lorem. Nam efficitur tellus vitae sem tincidunt aliquet. Aliquam dolor turpis, eleifend eget nisi id, interdum faucibus lacus. In hac habitasse platea dictumst. Nulla metus nulla, aliquet a eleifend vel, lacinia eget sem. Mauris eu lacinia elit. Nam hendrerit, libero sed euismod tempus, dolor enim consequat risus, eu maximus ligula quam at mauris. Proin at semper justo. Vivamus lacinia vel enim eget bibendum. Ut eget leo nec elit auctor facilisis maximus in quam. Maecenas ullamcorper ullamcorper nulla, eu fringilla mi eleifend eget. Ut diam nulla, suscipit sit amet augue vitae, dapibus viverra nunc. Aliquam consequat urna ipsum, at hendrerit diam pharetra eget. Nulla tincidunt ultricies enim, at maximus metus semper nec. Morbi at libero et ipsum convallis congue.

', 'image.jpg', '2', '2018-02-03');
INSERT INTO `blogdata`.`posts` (`title`, `preview`, `content`, `image`, `pages_pageid`, `date`) VALUES ('2 orem ipsum', 'Integer ligula erat, iaculis a sodales eu, commodo nec lorem. Nam efficitur tellus vitae sem tincidunt aliquet. Aliquam dolor turpis, eleifend eget nis', 'Integer ligula erat, iaculis a sodales eu, commodo nec lorem. Nam efficitur tellus vitae sem tincidunt aliquet. Aliquam dolor turpis, eleifend eget nisi id, interdum faucibus lacus. In hac habitasse platea dictumst. Nulla metus nulla, aliquet a eleifend vel, lacinia eget sem. Mauris eu lacinia elit. Nam hendrerit, libero sed euismod tempus, dolor enim consequat risus, eu maximus ligula quam at mauris. Proin at semper justo. Vivamus lacinia vel enim eget bibendum. Ut eget leo nec elit auctor facilisis maximus in quam. Maecenas ullamcorper ullamcorper nulla, eu fringilla mi eleifend eget. Ut diam nulla, suscipit sit amet augue vitae, dapibus viverra nunc. Aliquam consequat urna ipsum, at hendrerit diam pharetra eget. Nulla tincidunt ultricies enim, at maximus metus semper nec. Morbi at libero et ipsum convallis congue.

', 'image.jpg', '2', '2018-02-03');

INSERT INTO `blogdata`.`widgets` ( `header`, `body`, `site_sitename`) VALUES ('Search','Search for posts', 'Myblog');
INSERT INTO `blogdata`.`widgets` ( `header`, `body`, `site_sitename`) VALUES ('Popular posts','Most popular posts on this blog', 'Myblog');


